version: '3.8'
services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql-volume:/var/lib/mysql:rw
      - ./mysql:/docker-entrypoint-initdb.d/
    networks:
      - default

  nestjs-app:
    container_name: nestjs-app
    depends_on:
      - mysql-db
    build: ./nestjs
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./nestjs:/app
      - /app/node_modules
    networks:
      - default
  
  vuejs-app:
    container_name: vuejs-app
    build: ./vuejs
    restart: always
    env_file: ./.env
    ports:
      - $VUEJS_APP_LOCAL_PORT:$VUEJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./vuejs:/app
      - /app/node_modules
    networks:
      - default